version = "3.7.14"

maxColumn = 120
runner.dialect = scala213

align = most
align.tokens = [
  { code = "=>" }
  { code = "->" }
  { code = ":" }
  { code = "=" }
  { code = "with" }
]

continuationIndent.callSite = 2
continuationIndent.defnSite = 2

spaces.inImportCurlyBraces = false

newlines.beforeCurlyLambdaParams = true
newlines.afterCurlyLambdaParams = "preserve"

trailingCommas = always

rewrite.rules = [RedundantBraces]